# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Arthamios/delivery/OOP/OOP_arcade_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Arthamios/delivery/OOP/OOP_arcade_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Arthamios/delivery/OOP/OOP_arcade_2018/CMakeFiles /home/Arthamios/delivery/OOP/OOP_arcade_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Arthamios/delivery/OOP/OOP_arcade_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named units

# Build rule for target.
units: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 units
.PHONY : units

# fast build rule for target.
units/fast:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/build
.PHONY : units/fast

#=============================================================================
# Target rules for targets named arcade

# Build rule for target.
arcade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arcade
.PHONY : arcade

# fast build rule for target.
arcade/fast:
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/build
.PHONY : arcade/fast

#=============================================================================
# Target rules for targets named graphicals

# Build rule for target.
graphicals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphicals
.PHONY : graphicals

# fast build rule for target.
graphicals/fast:
	$(MAKE) -f CMakeFiles/graphicals.dir/build.make CMakeFiles/graphicals.dir/build
.PHONY : graphicals/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named games

# Build rule for target.
games: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 games
.PHONY : games

# fast build rule for target.
games/fast:
	$(MAKE) -f CMakeFiles/games.dir/build.make CMakeFiles/games.dir/build
.PHONY : games/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named tests_run

# Build rule for target.
tests_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_run
.PHONY : tests_run

# fast build rule for target.
tests_run/fast:
	$(MAKE) -f CMakeFiles/tests_run.dir/build.make CMakeFiles/tests_run.dir/build
.PHONY : tests_run/fast

# target to build an object file
component/Audio.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Audio.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Audio.o
.PHONY : component/Audio.o

# target to preprocess a source file
component/Audio.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Audio.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Audio.i
.PHONY : component/Audio.i

# target to generate assembly for a file
component/Audio.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Audio.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Audio.s
.PHONY : component/Audio.s

# target to build an object file
component/Sprite.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Sprite.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Sprite.o
.PHONY : component/Sprite.o

# target to preprocess a source file
component/Sprite.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Sprite.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Sprite.i
.PHONY : component/Sprite.i

# target to generate assembly for a file
component/Sprite.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Sprite.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Sprite.s
.PHONY : component/Sprite.s

# target to build an object file
component/Text.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Text.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Text.o
.PHONY : component/Text.o

# target to preprocess a source file
component/Text.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Text.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Text.i
.PHONY : component/Text.i

# target to generate assembly for a file
component/Text.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/component/Text.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/component/Text.s
.PHONY : component/Text.s

# target to build an object file
core/src/Core.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Core.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Core.o
.PHONY : core/src/Core.o

# target to preprocess a source file
core/src/Core.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Core.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Core.i
.PHONY : core/src/Core.i

# target to generate assembly for a file
core/src/Core.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Core.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Core.s
.PHONY : core/src/Core.s

# target to build an object file
core/src/Process.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Process.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Process.o
.PHONY : core/src/Process.o

# target to preprocess a source file
core/src/Process.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Process.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Process.i
.PHONY : core/src/Process.i

# target to generate assembly for a file
core/src/Process.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/Process.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/Process.s
.PHONY : core/src/Process.s

# target to build an object file
core/src/library/LibraryLoader.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoader.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoader.o
.PHONY : core/src/library/LibraryLoader.o

# target to preprocess a source file
core/src/library/LibraryLoader.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoader.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoader.i
.PHONY : core/src/library/LibraryLoader.i

# target to generate assembly for a file
core/src/library/LibraryLoader.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoader.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoader.s
.PHONY : core/src/library/LibraryLoader.s

# target to build an object file
core/src/library/LibraryLoaderException.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoaderException.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoaderException.o
.PHONY : core/src/library/LibraryLoaderException.o

# target to preprocess a source file
core/src/library/LibraryLoaderException.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoaderException.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoaderException.i
.PHONY : core/src/library/LibraryLoaderException.i

# target to generate assembly for a file
core/src/library/LibraryLoaderException.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/library/LibraryLoaderException.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/library/LibraryLoaderException.s
.PHONY : core/src/library/LibraryLoaderException.s

# target to build an object file
core/src/main.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/main.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/main.o
.PHONY : core/src/main.o

# target to preprocess a source file
core/src/main.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/main.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/main.i
.PHONY : core/src/main.i

# target to generate assembly for a file
core/src/main.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/main.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/main.s
.PHONY : core/src/main.s

# target to build an object file
core/src/scenes/Scene.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/Scene.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/Scene.o
.PHONY : core/src/scenes/Scene.o

# target to preprocess a source file
core/src/scenes/Scene.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/Scene.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/Scene.i
.PHONY : core/src/scenes/Scene.i

# target to generate assembly for a file
core/src/scenes/Scene.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/Scene.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/Scene.s
.PHONY : core/src/scenes/Scene.s

# target to build an object file
core/src/scenes/SceneFactory.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneFactory.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneFactory.o
.PHONY : core/src/scenes/SceneFactory.o

# target to preprocess a source file
core/src/scenes/SceneFactory.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneFactory.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneFactory.i
.PHONY : core/src/scenes/SceneFactory.i

# target to generate assembly for a file
core/src/scenes/SceneFactory.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneFactory.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneFactory.s
.PHONY : core/src/scenes/SceneFactory.s

# target to build an object file
core/src/scenes/SceneManager.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneManager.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneManager.o
.PHONY : core/src/scenes/SceneManager.o

# target to preprocess a source file
core/src/scenes/SceneManager.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneManager.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneManager.i
.PHONY : core/src/scenes/SceneManager.i

# target to generate assembly for a file
core/src/scenes/SceneManager.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SceneManager.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SceneManager.s
.PHONY : core/src/scenes/SceneManager.s

# target to build an object file
core/src/scenes/SharedData.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SharedData.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SharedData.o
.PHONY : core/src/scenes/SharedData.o

# target to preprocess a source file
core/src/scenes/SharedData.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SharedData.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SharedData.i
.PHONY : core/src/scenes/SharedData.i

# target to generate assembly for a file
core/src/scenes/SharedData.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/SharedData.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/SharedData.s
.PHONY : core/src/scenes/SharedData.s

# target to build an object file
core/src/scenes/exit/ExitScene.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/exit/ExitScene.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/exit/ExitScene.o
.PHONY : core/src/scenes/exit/ExitScene.o

# target to preprocess a source file
core/src/scenes/exit/ExitScene.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/exit/ExitScene.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/exit/ExitScene.i
.PHONY : core/src/scenes/exit/ExitScene.i

# target to generate assembly for a file
core/src/scenes/exit/ExitScene.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/exit/ExitScene.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/exit/ExitScene.s
.PHONY : core/src/scenes/exit/ExitScene.s

# target to build an object file
core/src/scenes/game/GameScene.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/game/GameScene.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/game/GameScene.o
.PHONY : core/src/scenes/game/GameScene.o

# target to preprocess a source file
core/src/scenes/game/GameScene.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/game/GameScene.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/game/GameScene.i
.PHONY : core/src/scenes/game/GameScene.i

# target to generate assembly for a file
core/src/scenes/game/GameScene.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/game/GameScene.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/game/GameScene.s
.PHONY : core/src/scenes/game/GameScene.s

# target to build an object file
core/src/scenes/menu/MainMenu.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/menu/MainMenu.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/menu/MainMenu.o
.PHONY : core/src/scenes/menu/MainMenu.o

# target to preprocess a source file
core/src/scenes/menu/MainMenu.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/menu/MainMenu.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/menu/MainMenu.i
.PHONY : core/src/scenes/menu/MainMenu.i

# target to generate assembly for a file
core/src/scenes/menu/MainMenu.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/menu/MainMenu.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/menu/MainMenu.s
.PHONY : core/src/scenes/menu/MainMenu.s

# target to build an object file
core/src/scenes/player_name/Cursor.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Cursor.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Cursor.o
.PHONY : core/src/scenes/player_name/Cursor.o

# target to preprocess a source file
core/src/scenes/player_name/Cursor.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Cursor.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Cursor.i
.PHONY : core/src/scenes/player_name/Cursor.i

# target to generate assembly for a file
core/src/scenes/player_name/Cursor.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Cursor.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Cursor.s
.PHONY : core/src/scenes/player_name/Cursor.s

# target to build an object file
core/src/scenes/player_name/PlayerName.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/PlayerName.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/PlayerName.o
.PHONY : core/src/scenes/player_name/PlayerName.o

# target to preprocess a source file
core/src/scenes/player_name/PlayerName.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/PlayerName.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/PlayerName.i
.PHONY : core/src/scenes/player_name/PlayerName.i

# target to generate assembly for a file
core/src/scenes/player_name/PlayerName.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/PlayerName.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/PlayerName.s
.PHONY : core/src/scenes/player_name/PlayerName.s

# target to build an object file
core/src/scenes/player_name/Row.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Row.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Row.o
.PHONY : core/src/scenes/player_name/Row.o

# target to preprocess a source file
core/src/scenes/player_name/Row.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Row.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Row.i
.PHONY : core/src/scenes/player_name/Row.i

# target to generate assembly for a file
core/src/scenes/player_name/Row.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/player_name/Row.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/player_name/Row.s
.PHONY : core/src/scenes/player_name/Row.s

# target to build an object file
core/src/scenes/utils/Button.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/utils/Button.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/utils/Button.o
.PHONY : core/src/scenes/utils/Button.o

# target to preprocess a source file
core/src/scenes/utils/Button.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/utils/Button.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/utils/Button.i
.PHONY : core/src/scenes/utils/Button.i

# target to generate assembly for a file
core/src/scenes/utils/Button.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/core/src/scenes/utils/Button.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/core/src/scenes/utils/Button.s
.PHONY : core/src/scenes/utils/Button.s

# target to build an object file
games/qix/src/Cell.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Cell.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Cell.o
.PHONY : games/qix/src/Cell.o

# target to preprocess a source file
games/qix/src/Cell.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Cell.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Cell.i
.PHONY : games/qix/src/Cell.i

# target to generate assembly for a file
games/qix/src/Cell.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Cell.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Cell.s
.PHONY : games/qix/src/Cell.s

# target to build an object file
games/qix/src/CellTest.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/CellTest.o
.PHONY : games/qix/src/CellTest.o

# target to preprocess a source file
games/qix/src/CellTest.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/CellTest.i
.PHONY : games/qix/src/CellTest.i

# target to generate assembly for a file
games/qix/src/CellTest.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/CellTest.s
.PHONY : games/qix/src/CellTest.s

# target to build an object file
games/qix/src/Converter.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Converter.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Converter.o
.PHONY : games/qix/src/Converter.o

# target to preprocess a source file
games/qix/src/Converter.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Converter.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Converter.i
.PHONY : games/qix/src/Converter.i

# target to generate assembly for a file
games/qix/src/Converter.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Converter.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Converter.s
.PHONY : games/qix/src/Converter.s

# target to build an object file
games/qix/src/ConverterTest.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/ConverterTest.o
.PHONY : games/qix/src/ConverterTest.o

# target to preprocess a source file
games/qix/src/ConverterTest.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/ConverterTest.i
.PHONY : games/qix/src/ConverterTest.i

# target to generate assembly for a file
games/qix/src/ConverterTest.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/ConverterTest.s
.PHONY : games/qix/src/ConverterTest.s

# target to build an object file
games/qix/src/Game.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Game.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Game.o
.PHONY : games/qix/src/Game.o

# target to preprocess a source file
games/qix/src/Game.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Game.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Game.i
.PHONY : games/qix/src/Game.i

# target to generate assembly for a file
games/qix/src/Game.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Game.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Game.s
.PHONY : games/qix/src/Game.s

# target to build an object file
games/qix/src/Map.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Map.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Map.o
.PHONY : games/qix/src/Map.o

# target to preprocess a source file
games/qix/src/Map.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Map.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Map.i
.PHONY : games/qix/src/Map.i

# target to generate assembly for a file
games/qix/src/Map.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Map.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Map.s
.PHONY : games/qix/src/Map.s

# target to build an object file
games/qix/src/MapTest.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/MapTest.o
.PHONY : games/qix/src/MapTest.o

# target to preprocess a source file
games/qix/src/MapTest.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/MapTest.i
.PHONY : games/qix/src/MapTest.i

# target to generate assembly for a file
games/qix/src/MapTest.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/MapTest.s
.PHONY : games/qix/src/MapTest.s

# target to build an object file
games/qix/src/Player.o:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Player.o
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Player.o
.PHONY : games/qix/src/Player.o

# target to preprocess a source file
games/qix/src/Player.i:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Player.i
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Player.i
.PHONY : games/qix/src/Player.i

# target to generate assembly for a file
games/qix/src/Player.s:
	$(MAKE) -f CMakeFiles/units.dir/build.make CMakeFiles/units.dir/games/qix/src/Player.s
	$(MAKE) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/games/qix/src/Player.s
.PHONY : games/qix/src/Player.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... units"
	@echo "... arcade"
	@echo "... graphicals"
	@echo "... re"
	@echo "... games"
	@echo "... edit_cache"
	@echo "... fclean"
	@echo "... tests_run"
	@echo "... component/Audio.o"
	@echo "... component/Audio.i"
	@echo "... component/Audio.s"
	@echo "... component/Sprite.o"
	@echo "... component/Sprite.i"
	@echo "... component/Sprite.s"
	@echo "... component/Text.o"
	@echo "... component/Text.i"
	@echo "... component/Text.s"
	@echo "... core/src/Core.o"
	@echo "... core/src/Core.i"
	@echo "... core/src/Core.s"
	@echo "... core/src/Process.o"
	@echo "... core/src/Process.i"
	@echo "... core/src/Process.s"
	@echo "... core/src/library/LibraryLoader.o"
	@echo "... core/src/library/LibraryLoader.i"
	@echo "... core/src/library/LibraryLoader.s"
	@echo "... core/src/library/LibraryLoaderException.o"
	@echo "... core/src/library/LibraryLoaderException.i"
	@echo "... core/src/library/LibraryLoaderException.s"
	@echo "... core/src/main.o"
	@echo "... core/src/main.i"
	@echo "... core/src/main.s"
	@echo "... core/src/scenes/Scene.o"
	@echo "... core/src/scenes/Scene.i"
	@echo "... core/src/scenes/Scene.s"
	@echo "... core/src/scenes/SceneFactory.o"
	@echo "... core/src/scenes/SceneFactory.i"
	@echo "... core/src/scenes/SceneFactory.s"
	@echo "... core/src/scenes/SceneManager.o"
	@echo "... core/src/scenes/SceneManager.i"
	@echo "... core/src/scenes/SceneManager.s"
	@echo "... core/src/scenes/SharedData.o"
	@echo "... core/src/scenes/SharedData.i"
	@echo "... core/src/scenes/SharedData.s"
	@echo "... core/src/scenes/exit/ExitScene.o"
	@echo "... core/src/scenes/exit/ExitScene.i"
	@echo "... core/src/scenes/exit/ExitScene.s"
	@echo "... core/src/scenes/game/GameScene.o"
	@echo "... core/src/scenes/game/GameScene.i"
	@echo "... core/src/scenes/game/GameScene.s"
	@echo "... core/src/scenes/menu/MainMenu.o"
	@echo "... core/src/scenes/menu/MainMenu.i"
	@echo "... core/src/scenes/menu/MainMenu.s"
	@echo "... core/src/scenes/player_name/Cursor.o"
	@echo "... core/src/scenes/player_name/Cursor.i"
	@echo "... core/src/scenes/player_name/Cursor.s"
	@echo "... core/src/scenes/player_name/PlayerName.o"
	@echo "... core/src/scenes/player_name/PlayerName.i"
	@echo "... core/src/scenes/player_name/PlayerName.s"
	@echo "... core/src/scenes/player_name/Row.o"
	@echo "... core/src/scenes/player_name/Row.i"
	@echo "... core/src/scenes/player_name/Row.s"
	@echo "... core/src/scenes/utils/Button.o"
	@echo "... core/src/scenes/utils/Button.i"
	@echo "... core/src/scenes/utils/Button.s"
	@echo "... games/qix/src/Cell.o"
	@echo "... games/qix/src/Cell.i"
	@echo "... games/qix/src/Cell.s"
	@echo "... games/qix/src/CellTest.o"
	@echo "... games/qix/src/CellTest.i"
	@echo "... games/qix/src/CellTest.s"
	@echo "... games/qix/src/Converter.o"
	@echo "... games/qix/src/Converter.i"
	@echo "... games/qix/src/Converter.s"
	@echo "... games/qix/src/ConverterTest.o"
	@echo "... games/qix/src/ConverterTest.i"
	@echo "... games/qix/src/ConverterTest.s"
	@echo "... games/qix/src/Game.o"
	@echo "... games/qix/src/Game.i"
	@echo "... games/qix/src/Game.s"
	@echo "... games/qix/src/Map.o"
	@echo "... games/qix/src/Map.i"
	@echo "... games/qix/src/Map.s"
	@echo "... games/qix/src/MapTest.o"
	@echo "... games/qix/src/MapTest.i"
	@echo "... games/qix/src/MapTest.s"
	@echo "... games/qix/src/Player.o"
	@echo "... games/qix/src/Player.i"
	@echo "... games/qix/src/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

