######################################################################
# Automatically generated by qmake (3.1) Wed Mar 6 20:04:44 2019
######################################################################

TEMPLATE = lib

QT += widgets	\
	charts \


# Directories
SOURCES += QtGraphic.cpp
HEADERS += QtGraphic.hpp IGraphic.hpp
DEFINES += ARCADE
