######################################################################
# Automatically generated by qmake (3.1) Wed Mar 6 20:04:44 2019
######################################################################

TEMPLATE = lib

QT += widgets	\


# Directories
SOURCES += QtGraphic.cpp ../../component/ASprite.cpp
HEADERS += QtGraphic.hpp ../IGraphic.hpp ../../component/ASprite.hpp
INCLUDEPATH += $$PWD/.. $$PWD/../../component
DEFINES += ARCADE
